import type { Metadata } from 'next';

import './globals.scss';

export const metadata: Metadata = {
  title: 'Interview App - Patryk Babula - Mobile Reality',
  description: 'Generated by create next app',
};

import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
